// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymxqdmojesynwqbiiscd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlteHFkbW9qZXN5bndxYmlpc2NkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NDA3ODksImV4cCI6MjA2MzUxNjc4OX0.IIajQ8qZDWG-NIjbJNM3i8GWKFuLt36A3qLJrgZwrPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);